function solution(myString) {
    myString = myString.replaceAll("a", "A");
    myString = myString.replaceAll("B", "b");
    myString = myString.replaceAll("C", "c");
    myString = myString.replaceAll("D", "d");
    myString = myString.replaceAll("E", "e");
    myString = myString.replaceAll("F", "f");
    myString = myString.replaceAll("G", "g");
    myString = myString.replaceAll("H", "h");
    myString = myString.replaceAll("I", "i");
    myString = myString.replaceAll("J", "j");
    myString = myString.replaceAll("K", "k");
    myString = myString.replaceAll("L", "l");
    myString = myString.replaceAll("M", "m");
    myString = myString.replaceAll("N", "n");
    myString = myString.replaceAll("O", "o");
    myString = myString.replaceAll("P", "p");
    myString = myString.replaceAll("Q", "q");
    myString = myString.replaceAll("R", "r");
    myString = myString.replaceAll("S", "s");
    myString = myString.replaceAll("T", "t");
    myString = myString.replaceAll("U", "u");
    myString = myString.replaceAll("V", "v");
    myString = myString.replaceAll("W", "w");
    myString = myString.replaceAll("X", "x");
    myString = myString.replaceAll("Y", "y");
    myString = myString.replaceAll("Z", "z");
    var answer = myString;
    return answer;
}